SYS-190 add github ci
shardeum/lib-archiver-discovery pull request #4
Opened 2024-07-08 18:49 UTC by TieDyedSheep

2024-07-09 22:24 UTC, muni-corn approved these changes

2024-07-09 22:25 UTC, muni-corn requested changes, later dismissed
oops. needs a `build` script or build phase to be skipped :grin:

2024-07-19 18:30 UTC, TieDyedSheep commented
> oops. needs a `build` script or build phase to be skipped 😁

refactored this and should have cleared up any issues you found before :D

2024-07-30 21:50 UTC, mhanson-github approved these changes

2024-07-30 21:57 UTC, merged